### ISSUE TITLE
How to use soap2rest plugin

### ISSUE THREAD

**Issue by ali-ghazi78** [adessoAG/kong-plugin-soap2rest#1]
Hello, 
Thanks for your great plugin and your contribution. 
I have a path like this:

```localhost:8000/hello_wsdl```
and this is a parameter in my **header**
```soapAction: "whereAreYou"```

Is there anyway that I can take the soapAction from the header and put it into my path?
something like this.
```localhost:8000/hello_wsdl/whereAreYou```

**Comment by DanielKraft** [comment]
Hallo,
This plugin is for simulating a WSDL interface and redirecting from the WSDL path to a REST API. The plugin is not intended to change the path of a WSDL request.

By default, the associated REST path is selected based on the passed openapi.yml (see the `config.openapi_yaml_path` parameter).

For special cases, we have added the parameter `config.operation_mapping`. However, this parameter is intended for paths with path parameters like `/person/{id}/pet/{pet_id}`.
