### ISSUE TITLE
Transform soap2rest to rest2soap

### ISSUE THREAD

**Issue by DanielKraft** [adessoAG/kong-plugin-soap2rest#4]
> Thank you for sharing your work. I have a question about a slightly different scenario. In this case, my application expects SOAP requests. I want to use API Manager to receive REST requests from a client (outside world), convert them to SOAP requests with Kong API Gateway, send SOAP message to my application, get a SOAP response back from the application, convert it to REST with Kong API Gateway, and send it back to the client. Do you think I can reuse some of what you built? If not, would you share the general outline I should follow? Thank you in advance.

_Originally posted by @bbekdas in https://github.com/adessoSE/kong-plugin-soap2rest/issues/3#issuecomment-1095255107_

**Comment by DanielKraft** [comment]
First of all: please open a new issue next time when it comes to questions of a different context.

> Do you think I can reuse some of what you built? 

In principle, the structure of these plugins could be used for this. 

However, the parsing of the WSDL and the OpenAPI would have to be adapted to their needs (see [wsdl_handler.lua](https://github.com/adessoSE/kong-plugin-soap2rest/blob/master/kong/plugins/soap2rest/wsdl_handler.lua) and [openapi_handler.lua](https://github.com/adessoSE/kong-plugin-soap2rest/blob/master/kong/plugins/soap2rest/openapi_handler.lua)). Subsequently, the conversion of the requests (from SOAP to REST) and the responses (from REST to SOAP) must be changed (see [request_handler.lua](https://github.com/adessoSE/kong-plugin-soap2rest/blob/master/kong/plugins/soap2rest/request_handler.lua) and [response_handler.lua](https://github.com/adessoSE/kong-plugin-soap2rest/blob/master/kong/plugins/soap2rest/response_handler.lua)).

I would therefore recommend you to fork this repository. Don't worry if you are new to Lua, this was my first Lua project and Kong plugin too.

**Comment by bbekdas** [comment]
Thank you very much @DanielKraft!
